var glob = require("glob");
var path = require("path");
var fs = require("fs");

var addon_name = "ember-fhir-adapter";
// Get the addon models
var models = glob.sync(path.join("addon", "models", "*.js"));

for (var model in models) {
  var fileName = models[model].split(path.sep).pop();
  var modelName = fileName.replace(/\.[^/.]+$/, "");
  var modelJSName = modelName.replace(/-/g, "_");
  var importString = "//Autogenerated by ../../build_app.js\nimport " + modelJSName + " from '" + path.join(addon_name, "models", modelName) + "';\nexport default " + modelJSName + ";";
  // console.log(path.join("app", "models", modelName + ".js"));
  // console.log(importString);
  fs.writeFileSync(path.join("app", "models", modelName + ".js"), importString);
}
