// Generated by CoffeeScript 1.9.3
import DS from 'ember-data';
var Address;

Address = DS.Model.extend({
  use: DS.attr('string'),
  text: DS.attr('string'),
  line: DS.attr('string'),
  city: DS.attr('string'),
  state: DS.attr('string'),
  zip: DS.attr('string'),
  country: DS.attr('string'),
  period: DS.belongsTo('period')
});

export default Address;
