// Generated by CoffeeScript 1.9.3
import DS from 'ember-data';
var Animal;

Animal = DS.Model.extend({
  species: DS.belongsTo('codeable-concept'),
  breed: DS.belongsTo('codeable-concept'),
  genderStatus: DS.belongsTo('codeable-concept')
});

export default Animal;
