// Generated by CoffeeScript 1.9.3
import DS from 'ember-data';
var Coding;

Coding = DS.Model.extend({
  system: DS.attr('string'),
  version: DS.attr('string'),
  code: DS.attr('string'),
  display: DS.attr('string'),
  primary: DS.attr('boolean'),
  valueSet: DS.belongsTo('resource-reference'),
  toString: function() {
    return this.get('display') || this.get('code');
  }
});

export default Coding;
