// Generated by CoffeeScript 1.9.3
import DS from 'ember-data';
var ContactPoint;

ContactPoint = DS.Model.extend({
  system: DS.attr('string'),
  value: DS.attr('string'),
  use: DS.attr('string')
});

export default ContactPoint;
