// Generated by CoffeeScript 1.9.3
import DS from 'ember-data';
var Contact;

Contact = DS.Model.extend({
  relationship: DS.hasMany('codeable-concept'),
  name: DS.belongsTo('human-name'),
  telecom: DS.hasMany('contact-point'),
  address: DS.belongsTo('address'),
  gender: DS.attr('string'),
  organization: DS.belongsTo('reference')
});

export default Contact;
