// Generated by CoffeeScript 1.9.3
import DS from 'ember-data';
var Dosage;

Dosage = DS.Model.extend({
  asNeededBoolean: DS.attr('boolean'),
  asNeededCodeableConcept: DS.belongsTo('codeableConcept'),
  site: DS.belongsTo('codeableConcept'),
  route: DS.belongsTo('codeableConcept'),
  method: DS.belongsTo('codeableConcept'),
  quantity: DS.belongsTo('quantity')
});

export default Dosage;
