// Generated by CoffeeScript 1.9.3
import DS from 'ember-data';
var EmberItem;

EmberItem = DS.Model.extend({
  parameter: DS.belongsTo("extension"),
  active: DS.attr("boolean", {
    defaultValue: false
  }),
  componentName: DS.attr("string"),
  changed: (function() {
    return 1;
  }).property("parameter.valueString", "parameter.valueRange.low.value", "parameter.valueRange.high.value", "parameter.valueCodeableConcept.coding.@each.code", "parameter.valueCodeableConcept.coding.@each.system")
});

export default EmberItem;
