// Generated by CoffeeScript 1.9.3
import Em from 'ember';
import DS from 'ember-data';
import CodeableMixin from '../mixins/codeable';
import DateableMixin from '../mixins/dateable';
var Encounter;

Encounter = DS.Model.extend(CodeableMixin, DateableMixin, {
  identifier: DS.hasMany('identifier'),
  status: DS.attr('string'),
  "class": DS.attr('string'),
  type: DS.hasMany('codeable-concept'),
  subject: DS.belongsTo('resource-reference'),
  participant: DS.hasMany('participant'),
  fulfills: DS.belongsTo('resource-reference'),
  period: DS.belongsTo('period'),
  length: DS.belongsTo('quantity'),
  reason: DS.belongsTo('codeable-concept'),
  indication: DS.belongsTo('resource-reference'),
  priority: DS.belongsTo('codeable-concept'),
  hospitalization: DS.belongsTo('hospitalization'),
  location: DS.hasMany('location'),
  serviceProvider: DS.belongsTo('resource-reference'),
  partOf: DS.belongsTo('resource-reference'),
  text: (function() {
    var ref, ref1;
    return ((ref = this.get('type.firstObject.text')) != null ? (ref1 = ref.match(/:\s+([^(]+)\s+\(/)) != null ? ref1[1] : void 0 : void 0) || this.get('code.firstObject.text');
  }).property('type'),
  startDate: Em.computed('period.start', function() {
    return this.get('period.start');
  }),
  endDate: Em.computed('period.end', function() {
    return this.get('period.end');
  })
});

export default Encounter;
