// Generated by CoffeeScript 1.9.3
import DS from 'ember-data';
var Extension;

Extension = DS.Model.extend({
  url: DS.attr('string'),
  value: DS.attr(),
  valueString: DS.attr("string"),
  valueCodeableConcept: DS.belongsTo("codeable-concept"),
  valueRange: DS.belongsTo("range")
});

export default Extension;
