// Generated by CoffeeScript 1.9.3
import DS from 'ember-data';
var Hospitalization;

Hospitalization = DS.Model.extend({
  preAdmissionIdentifier: DS.belongsTo('identifier'),
  origin: DS.belongsTo('resource-reference'),
  admitSource: DS.belongsTo('codeable-concept'),
  period: DS.belongsTo('period'),
  accomodation: DS.hasMany('accomodation'),
  diet: DS.belongsTo('codeable-concept'),
  specialCourtesy: DS.hasMany('codeable-concept'),
  specialArrangement: DS.hasMany('codeable-concept'),
  destination: DS.belongsTo('resource-reference'),
  dischargeDisposition: DS.belongsTo('codeable-concept'),
  dischargeDiagnosis: DS.belongsTo('resource-reference'),
  reAdmission: DS.attr('boolean')
});

export default Hospitalization;
