// Generated by CoffeeScript 1.9.3
import DS from 'ember-data';
var Identifier;

Identifier = DS.Model.extend({
  use: DS.attr('string'),
  label: DS.attr('string'),
  system: DS.attr('string'),
  value: DS.attr('string'),
  period: DS.belongsTo('period'),
  assigner: DS.belongsTo('resource-reference')
});

export default Identifier;
