// Generated by CoffeeScript 1.9.3
import Ember from 'ember';
import DS from 'ember-data';
var Patient;

Patient = DS.Model.extend({
  identifier: DS.hasMany('identifier'),
  name: DS.hasMany('human-name'),
  telecom: DS.hasMany('contact-point'),
  gender: DS.attr('string')
  birthDate: DS.attr('date'),
  deceasedBoolean: DS.attr('boolean'),
  deceasedDateTime: DS.attr('date'),
  address: DS.hasMany('address'),
  maritalStatus: DS.belongsTo('codeable-concept'),
  multipleBirthBoolean: DS.attr('boolean'),
  multipleBirthInteger: DS.attr(),
  photo: DS.hasMany('attachment'),
  contact: DS.hasMany('contact'),
  animal: DS.belongsTo('animal'),
  communication: DS.hasMany('codeable-concept'),
  careProvider: DS.hasMany('reference'),
  managingOrganization: DS.belongsTo('reference'),
  link: DS.hasMany('link'),
  active: DS.attr('boolean')
});

export default Patient;
