// Generated by CoffeeScript 1.9.3
import DS from 'ember-data';
var Response;

Response = DS.Model.extend({
  identifier: DS.attr('string'),
  outcome: DS.attr('string'),
  total: DS.attr(),
  parameter: DS.hasMany('extension'),
  first: DS.hasMany('extension'),
  previous: DS.hasMany('extension'),
  next: DS.hasMany('extension'),
  last: DS.hasMany('extension'),
  reference: DS.hasMany('resource-reference')
});

export default Response;
