// Generated by CoffeeScript 1.9.3
import DS from 'ember-data';
var Animal;

Animal = DS.Model.extend({
  species: DS.belongsTo('codeable-concept', {embedded: true}),
  breed: DS.belongsTo('codeable-concept', {embedded: true}),
  genderStatus: DS.belongsTo('codeable-concept', {embedded: true})
});

export default Animal;
