// Generated by CoffeeScript 1.9.3
import DS from 'ember-data';
var Attachment;

Attachment = DS.Model.extend({
  contentType: DS.attr('string'),
  language: DS.attr('string'),
  url: DS.attr('string'),
  size: DS.attr(),
  title: DS.attr('string')
});

export default Attachment;
