// Generated by CoffeeScript 1.9.3
import Em from 'ember';
import DS from 'ember-data';
var Condition;

Condition = DS.Model.extend({
  identifier: DS.hasMany('identifier', {embedded: true}),
  subject: DS.belongsTo('resource-reference', {embedded: true}),
  encounter: DS.belongsTo('resource-reference', {embedded: true}),
  asserter: DS.belongsTo('resource-reference', {embedded: true}),
  dateAsserted: DS.attr('date'),
  code: DS.belongsTo('codeable-concept', {embedded: true}),
  category: DS.belongsTo('codeable-concept', {embedded: true}),
  status: DS.attr('string'),
  certainty: DS.belongsTo('codeable-concept', {embedded: true}),
  severity: DS.belongsTo('codeable-concept', {embedded: true}),
  onsetDate: DS.attr('date'),
  abatementDate: DS.attr('date'),
  abatementBoolean: DS.attr('boolean'),
  location: DS.hasMany('location', {embedded: true}),
  notes: DS.attr('string')
});

export default Condition;
