// Generated by CoffeeScript 1.9.3
import DS from 'ember-data';
var Dosage;

Dosage = DS.Model.extend({
  asNeededBoolean: DS.attr('boolean'),
  asNeededCodeableConcept: DS.belongsTo('codeableConcept', {embedded: true} ),
  site: DS.belongsTo('codeableConcept', {embedded: true} ),
  route: DS.belongsTo('codeableConcept', {embedded: true} ),
  method: DS.belongsTo('codeableConcept', {embedded: true} ),
  quantity: DS.belongsTo('quantity', {embedded: true} ),
  rate: DS.belongsTo('ratio', {embedded: true}),
  maxDosePerPeriod: DS.belongsTo('ratio', {embedded: true})
});

export default Dosage;
