// Generated by CoffeeScript 1.9.3
import DS from 'ember-data';
var Duration;

Duration = DS.Model.extend({
  low: DS.belongsTo('quantity', {embedded: true}),
  high: DS.belongsTo('quantity', {embedded: true})
});

export default Duration;
