// Generated by CoffeeScript 1.9.3
import Em from 'ember';
import DS from 'ember-data';
import CodeableMixin from '../mixins/codeable';
import DateableMixin from '../mixins/dateable';
var Encounter;

Encounter = DS.Model.extend(CodeableMixin, DateableMixin, {
  identifier: DS.hasMany('identifier', {embedded: true}),
  status: DS.attr('string'),
  "class": DS.attr('string'),
  type: DS.hasMany('codeable-concept', {embedded: true}),
  patient: DS.belongsTo('reference', {embedded: true}),
  participant: DS.hasMany('encounter-participant', {embedded: true}),
  fulfills: DS.belongsTo('reference', {embedded: true}),
  period: DS.belongsTo('period', {embedded: true}),
  length: DS.belongsTo('duration', {embedded: true}),
  reason: DS.hasMany('codeable-concept', {embedded: true}),
  indication: DS.hasMany('reference', {embedded: true}),
  priority: DS.belongsTo('codeable-concept', {embedded: true}),
  hospitalization: DS.belongsTo('encounter-hospitalization', {embedded: true}),
  location: DS.hasMany('encounter-location', {embedded: true}),
  serviceProvider: DS.belongsTo('reference', {embedded: true}),
  partOf: DS.belongsTo('resource-reference', {embedded: true}),
  episodeOfCare: DS.belongsTo('reference', {embedded: true}),
  incomingReferralRequest: DS.hasMany('reference', {embedded: true}),
  statusHistory: DS.hasMany('encounter-status-history', {embedded: true})
});

export default Encounter;
