// Generated by CoffeeScript 1.9.3
import DS from 'ember-data';
var HumanName;

HumanName = DS.Model.extend({
  use: DS.attr('string'),
  text: DS.attr('string'),
  family: DS.attr('string'),
  given: DS.attr('string'),
  prefix: DS.attr('string'),
  suffix: DS.attr('string'),
  period: DS.belongsTo('period'),

  toString: (function(){
    return this.get('family') + ', ' + this.get('given');
  })

});

export default HumanName;
