// Generated by CoffeeScript 1.9.3
import DS from 'ember-data';
var Medication;

Medication = DS.Model.extend({
  name: DS.attr('string'),
  code: DS.belongsTo('codeableConcept'),
  isBrand: DS.attr('boolean'),
  manufacturer: DS.belongsTo('resource-reference'),
  kind: DS.attr('string'),
  text: (function() {
    var ref, ref1;
    return ((ref = this.get('name')) != null ? (ref1 = ref.match(/:\s+([^(]+)\s+\(/)) != null ? ref1[1] : void 0 : void 0) || this.get('name');
  }).property('name')
});

export default Medication;
