// Generated by CoffeeScript 1.9.3
import DS from 'ember-data';
var Observation;

Observation = DS.Model.extend({
  name: DS.belongsTo('codeable-concept'),
  valueQuantity: DS.belongsTo('quantity'),
  valueCodeableConcept: DS.belongsTo('codeable-concept'),
  valueDateTime: DS.attr('date'),
  valuePeriod: DS.belongsTo('period'),
  valueString: DS.attr('string'),
  interpretation: DS.belongsTo('codeable-concept'),
  comments: DS.attr('string'),
  appliesDateTime: DS.attr('date'),
  appliesPeriod: DS.belongsTo('period'),
  issued: DS.attr('date'),
  status: DS.attr('string'),
  reliability: DS.attr('string'),
  bodySite: DS.belongsTo('codeable-concept'),
  method: DS.belongsTo('codeable-concept'),
  identifier: DS.belongsTo('identifier'),
  subject: DS.belongsTo('reference'),
  specimen: DS.belongsTo('reference'),
  performer: DS.hasMany('reference'),
  encounter: DS.belongsTo('reference'),
  isCoded: function(system, code) {
    return this.get('name.coding').mapBy('code').indexOf(code) > -1;
  },
  text: (function() {
    if (this.get('name.text') !== "") {
      return this.get('name.text').match(/:\s+([^(]+)\s+\(/)[1];
    } else {
      return "";
    }
  }).property('name')
});

export default Observation;
