// Generated by CoffeeScript 1.9.3
import DS from 'ember-data';
var Quantity;

Quantity = DS.Model.extend({
  value: DS.attr('number'),
  comparator: DS.attr('string'),
  units: DS.attr('string'),
  system: DS.attr('string'),
  code: DS.attr('string')
});

export default Quantity;
