// Generated by CoffeeScript 1.9.3
import DS from 'ember-data';
var Ratio;

Ratio = DS.Model.extend({
  numerator: DS.belongsTo('quantity', {embedded: true}),
  denominator: DS.belongsTo('quantity', {embedded: true})
});

export default Ratio;
