// Generated by CoffeeScript 1.9.3
import DS from 'ember-data';
var Reference;

Reference = DS.Model.extend({
  reference: DS.attr('string'),
  display: DS.attr('string')
});

export default Reference;
